<?php

// $Id$


/**
 * @file 
 * This module provides integration for Drupal's upload module
 * with the remig module
 */


 /**
  * Implementation of hook_media_register
  * @return 
  *   array
  */
function media_upload_media_register() {
  $registration = array(
    'media_upload_container' => array(
      // human readable name
      'name' => t('Media Upload container'),
      'uri' => 'file',
      // kind of item, one of     
      // container, format, insert, post_format
      'kind' => array(
        'container' => array(
          'types' => '*',
          'description' => t('Drupal uploaded files'), 
        )
      ),
      // human readable description
      'description' => t('Provides integration with Drupal\'s Upload module'),
      // fields
      'fields' => array('attachments'),
    ),
     
    // display the file
    'media_upload_display' => array(
      // human readable name
      'name' => 'Media Upload display'),
      'uri' => 'file',
      // kind of item, one of     
      // container, format, insert, post_format
      'kind' => array(
        'formater' => array(
          'types' => '*',
          'description' => t('Drupal uploaded files display'), 
        )
      ),
      // human readable description
      'description' => t('Provides integration with Drupal\'s Upload module'),
      // fields
      'fields' => array(),
     
    );
  return $registration;
}


/**
 * Implementation of hook_media_user_files_select
 *
 * @param string $node_type
 * @param string $field
 * @param int $uid
 */
function media_upload_media_user_files_select($node_type, $field, $uid) {
  return array(
   t('Add files') => array(
       t('New file') => array(
         'form' => media_upload_display_upload_form(),
       ),
       t('SWF') => array( 
        'form' => array('#value' => 'this would be the SWF upload function'),
      )
    )
  );
}



/**
 * Display the upload form for the tab 
 * @return string
 */ 
function media_upload_display_upload_form() {
  $form['media_upload']['upload'] = array(
    '#type' => 'file',
    '#title' => t('Upload your file'),
    '#size' => 30,
   );
   return $form;
}